### ISSUE TITLE
Proposed architecture and metadata schema

### ISSUE THREAD

**Issue by gregjd** [sunlightpolicy/opendatapoliciesstatic#15]
## Documents (`_documents`)

An individual document in the `_documents` directory represents a single policy not only by _place_ but also _date_. Thus, if a city has passed multiple versions of an open-data policy on different dates, these will be represented as different documents. All documents are Markdown (`.md`) files.

There is no hierarchy within the `_documents` directory; it is only a collection of individual documents. But users will still be able to easily browse documents thanks to _aggregation pages_ (see section below).

Each document's metadata will have the following fields:

- `place`: See the guidelines for `place` in the _Lookup tables_ section below.
- `date`: The date the policy was passed or signed, in `YYYY-MM-DD` format, i.e. `2016-12-31`.
  - One limitation of this system is that we don't have a way to handle multiple policies for the same location passed on the same date (whether through different legal means or the same legal means). It is extremely unlikely that we will ever face this, but if we do, we can cross that bridge when we get there.
- `legal_std`: This field represents the legal means of enactment. It is a standardized field, unlike `legal_custom`. The allowable values are:
  - `executive`: This is an order, memo, or policy that was signed by the chief executive or some other administrator.
  - `legislative`: This is a resolution that was passed by the legislative body or board.
  - `both`: This was passed by the legislative body or board _and_ signed by the chief executive.
  - `other`: This is a policy that was created through other means, such as judicial action.
- `legal_custom`: This _optional_ field represents the legal means of enactment, and is intended to use terms preferred by the government or agency in question, rather than the generic terms listed in `legal_std`. Examples of such terms include "Local law," "City manager's order," and "Administrative memo."
- `policy_url`: The URL of where to find the policy online. Preferably, the page linked to should be HTML or plain text, not a PDF. (And if it is a PDF, searchable ones are preferred over scanned image ones.)
- `display_policy`: Should this policy be listed? This field is _optional_ and assumed to be `true`; you only need to provide a value if you wish to manually specify`false` (if the policy shouldn't be listed for some reason).

Finally, the actual file names should be exactly the same as `place` and `date` concatenated with a hyphen. For example, if Boston passes an open-data policy on Jan 1, 2016, then its file name should be `boston-ma-2016-01-01.md`.

Note that file names are what determine document URLs. URLs will take the form: `http://www.opendatapolicies.org/doc/boston-ma-2016-01-01/`.

## Lookup tables (`_data`)

The primary purpose of the lookup tables is to prevent the duplication of metadata. For example, we wouldn't want each policy to list its state(s) using both two-letter postal abbreviations and the spelled-out state names; instead, it's better to only list the two-letter abbreviation and then have a separate table that gives each state abbreviation's corresponding full name as well as any other state metadata.

There will be two lookup tables: `states.csv` and `places.yaml`. They will be located in the `_data` directory. Read more about Jekyll's data files [here](https://jekyllrb.com/docs/datafiles/).

`states.csv` will contain two fields:
- `state_code`: The two-letter postal abbreviation for the state, i.e. `PA`, `MD`, `NY`.
- `state_name`:  The spelled-out version of the state name (not including "State of" or "Commonwealth of"), i.e. `Pennsylvania`, `Maryland`, `New York`.

This information will only be used on the state aggregation pages described below.

`places.yaml` contains data specific to a _place_ rather than an individual policy. It will need to be added any time a new policy is added for a place with no existing policy on the site. Its fields will be:
- `place`: A unique identifier for the place. In general, use the following rules:
  - Non-county municipalities should use the form `atlanta-ga`
  - Counties should use the form `montgomery-county-pa`
  - Consolidated city-counties should use the form `philadelphia-pa` (i.e. do not include "county")
  - [Independent cities](https://en.wikipedia.org/wiki/Independent_city_(United_States)) (mostly in Virginia) should include "city" to avoid ambiguity, i.e. `fairfax-city-va`
  - For other agencies, use discretion, with attention toward the identifier being unique and not one that will be needed for another place. Examples: `bart`, `port-authority-ny-nj`, `ny-mta`, `wmata`, `twin-cities-metro-council`, `boston-mapc`, `navajo-nation`, `metro-wash-airports`
- `name_full`: The full official name of the jurisdiction or agency. Examples:
  - City and County of San Francisco
  - Bay Area Rapid Transit District
  - State of Rhode Island and Providence Plantations
  - Lexington-Fayette Urban County Government
  - Louisville Metro Government
  - City of New York
  - Consolidated Municipality of Carson City
- `name_short`: A popular shorter name used to refer to the place or agency. All counties and county-equivalents should be followed by the word _County_. Only include "City" at the end of a name if it's officially part of the name (i.e. Salt Lake City), unofficially part of the name (i.e. New York City), or is necessary to distinguish it from a county of the same name (i.e. Baltimore City, versus Baltimore County). Consolidated city-counties generally should not include "City" or "County." Examples:
  - San Francisco
  - Bay Area Rapid Transit
  - Rhode Island
  - Lexington
  - Louisville
  - New York City
  - Carson City
- `states`: A list of all states the place falls under. For most places, this will just be one state, i.e. `['PA']`. But if the place in question is a multi-state agency, then your format will look like `['DC', 'MD', 'VA']`. Note the quotation marks and brackets.
- `type`: Indicates the type of government/agency whose policy it is. The default is `local`. The only allowable types are:
  - `state` — to be used for the 50 states (both for overall state policies as well as those of any state agencies) plus DC and US territories
  - `local` — to be used for all state subdivisions (cities, towns, counties, school districts, etc.)
  - `multi` — to be used for any agency whose jurisdiction crosses state lines but is not part of the federal government (i.e. a multi-state transit authority)
  - `usa` — to be used for US federal government agencies (if we ever add them)
  - `canada` — to be used for anything in Canada (if we ever add them)
- `x`: The longitude in degrees East–West. Example: `-112.0740` (negative indicates West)
- `y`: The latitude in degrees North–South. Example: `33.4484` (positive indicates North)
- `display_map`: Should this place be shown on the map of places? Only indicate `false` if it shouldn't be; otherwise do not specify a value (`true` will be assumed).
- `wwc`: Is this city a What Works City? Only indicate `true` if it is; otherwise do not specify a value (`false` will be assumed).

## Aggregation pages

These pages are intended to provide a user-friendly way of accessing the policies. You wouldn't want people to have to sort through every file in the `_documents` directory!

Each `place` will have a page that lists all of its policies. Many will just have one listed, but any place that has passed multiple versions of a policy will have multiple listed. (Maybe in the future we can even implement some sort of version comparison?)

But how will you find these pages? There will also be state-based aggregation pages, listing all the places within that state. (Remember, since a place can fall under multiple states, these state pages list all places for which that state is included in the `states` list variable.) When you click on _Browse_ on the site, you will be taken to a page listing all states.

In the future, we could add other aggregation pages or filtering options, such as based on year, legal means of enactment, WWC vs. non-WWC, etc.

As we have discussed, the website will also have a map page, with a map of the places. I think it makes sense to have two maps:
- one map that only shows places (as points), and clicking on a place takes you to that place's aggregation page
- another map that only shows states (as polygons), and clicking on a state takes you to that state's aggregation page

The maps could even just be included on the _Browse_ page (which lists all states).

## A final note

The main goal here is to have a flexible framework for the future. Obviously, many of the details above can be changed later on, but I want to make sure that we have room so that we're not going to break URLs or otherwise structure our data in a way that makes life difficult in the future.

For example, note that neither the directory structure nor the URLs nest policies within states. This is specifically to allow policies for government agencies that may cross state borders.

**Comment by gregjd** [comment]
Update:

Jekyll can't actually support having the "aggregation pages" mentioned above without using plugins.  We could maybe go down that road someday, but we don't need to for now. 

We can just manually create state pages for now: https://christianspecht.de/2014/10/25/separate-pages-per-tag-category-with-jekyll-without-plugins/

And for now we can say goodbye to having place pages, and instead each state page can look like this: https://christianspecht.de/tags/ — with a list of places, and each of the policies listed directly under its place. Honestly, this is probably a better solution for now anyway, since most places will only have one policy version.

**Comment by gregjd** [comment]
Basically implemented.

To-do: move this to a README in the repo (and make edits where I've done things differently than what's above).

**Comment by SLarrick** [comment]
This is all awesome. A great start to adding more structure to our policy repo with a metadata structure.

A few quick thoughts: 
- ``legal_std`` can be refined a bit, I think. Will say more on this later.
- Sometimes cities pass two open data policies simultaneously (say a resolution and an administrative policy). Does that present a problem for the document URLs?
- Are any of these fields informed by existing legal data standards or existing legal data documentation/schema? If so, it would be great to know which, and if not, should we consider?
- the ``places.yaml`` table seems to contain a lot information we don't really care about. It's fine to be more accurate if that doesn't add any time burden to maintenance/update (if it's automated) or alternatively if I'm missing something and it does provide us/our users with more functionality for the core use case of the site.  Otherwise, I'm not sure if, say, adding both the ``name_full`` and ``name_short`` is needed?
- encoding metadata tags into specific sections of policy (say to tag an example of one of our policy guidelines, or to tag the way a section is functioning, or a topic a section is covering) is an intermediate goal of this project to allow for more analysis and more granular comparison of policies across jurisdictions. Does your current architecture plan for this down the road?
