### ISSUE TITLE
Seattle CTO policy is combined with the Executive Order

### ISSUE THREAD

**Issue by SLarrick** [sunlightpolicy/opendatapoliciesstatic#19]
These need to be separated, with a new file added for the CTO policy

**Comment by SLarrick** [comment]
@gregjd

**Comment by gregjd** [comment]
CTO policy: http://www.opendatapolicies.org/doc/seattle-wa-2016-02-01/
Executive order: http://www.opendatapolicies.org/doc/seattle-wa-2016-02-26/

Though the CTO policy text is all one blob (which is how it was before). Needs to be separated into paragraphs, but proper paragraph separation is a separate site-wide issue.
