### ISSUE TITLE
Add states back to map

### ISSUE THREAD

**Issue by krusynth** [sunlightpolicy/opendatapoliciesstatic#3]
- [ ] Create a new collection for states
- [ ] Add a file for each state
- [ ] Iterate over these for the map json

These state pages won't be visible anywhere else on the site.

**Comment by gregjd** [comment]
Addressed by having a page that lists states: http://www.opendatapolicies.org/browse/states/

If we add state policies in the future, that will be handled when it happens. I may add a map with states someday (or add states to the places map), but not for now.
