### ISSUE TITLE
Tulsa 2015 executive order included in the Raleigh policy, but not where it should be

### ISSUE THREAD

**Issue by SLarrick** [sunlightpolicy/opendatapoliciesstatic#78]
See: http://www.opendatapolicies.org/doc/raleigh-nc-2012/ (Tulsa's 2015 EO is included after the 2012 Raleigh policy)

And see also: http://www.opendatapolicies.org/doc/tulsa-ok-2015/ (labelled as the 2015 EO but actually the 2012 Council Resolution)

**Comment by gregjd** [comment]
Resolved.

http://www.opendatapolicies.org/doc/raleigh-nc-2012-02-07/
http://www.opendatapolicies.org/doc/tulsa-ok-2015-12-21/
